In [1]:
import numpy as np
import gym
import random as r

In [2]:
# Create env
env = gym.make("FrozenLake-v0")

In [16]:
# Create Q-table
action_size = env.action_space.n #cols
state_size = env.observation_space.n #rows

qtable = np.zeros((state_size, action_size))
print(qtable)
print("size: {}".format(qtable.shape))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
size: (16, 4)


In [17]:
# Model hyperparams
total_episodes = 10 # num training runs
learning_rate = 0.8 # step-size multiplier
max_steps = 99 # max num steps in a training run
gamma = 0.95 # discount for future rewards given last action

# Explore params
eps = 1.0 # exlore probability
max_eps = 1.0 # starting explore probability
min_eps = 0.01 # min explore probability (i.e. 0.99 prob to use Q-table)
decay = 0.005 # discount for exploration vs. exploitation 
